### ISSUE TITLE
reposition out-of-place discourse units created to replace missing words missing from OCHRE

### ISSUE THREAD

**Issue by Gertrudius** [oaregithub/oare_mono#940]
When we set about reconstructing words that were left out of the OCHRE export, our policy was to set the new parent_uuid as the uuid of the top discourseUnit. While this was the right course of action, it can cause a situation in which they are correctly ordered within discourse, which places them in between phrases or words from the block of phrases that they were originally attached to. Since they still refer to the top discourseUnit as their parent, this will prevent them from displaying properly until we can assign them an appropriate parent_uuid within their original block (ideally the one of their actual parent if it still remains).

**Comment by edstratford** [comment]
This issue has been moved to oare_sql repo.
